In [128]:
import numpy as np
x = np.linspace(0,5,2) #ignore this points for now
x

array([0., 5.])

In [129]:
x

array([0., 5.])

In [130]:
x[0], x[1] = 5.65, 8

In [131]:
x

array([5.65, 8.  ])

In [132]:
y = np.linspace(0,3, 2) #ignore this points for now
y

array([0., 3.])

In [133]:
y[0], y[1] = 0, 0.8

In [134]:
y

array([0. , 0.8])

In [135]:
# How many points do you want to learn between 2 points?
i_want = 50 #points

In [136]:
point = i_want+2

In [137]:
a = np.linspace(0,0, i_want)
b = np.linspace(0,0, i_want)

In [145]:
for i in range(i_want):
  x_step = (x[1]-x[0])/(point)
  a[i] = x[0] + (i+1)*x_step

  y_step = (y[1]-y[0])/(point)
  b[i] = y[0] + (i+1)*y_step

print("X Points")
for j in range(len(a)):
  print(a[j], "/n")
print ("Y Points")
for l in range(len(b)):
  print(b[l], "/n")


X Points
5.695192307692308 /n
5.740384615384616 /n
5.785576923076923 /n
5.830769230769231 /n
5.875961538461539 /n
5.921153846153846 /n
5.966346153846154 /n
6.0115384615384615 /n
6.05673076923077 /n
6.101923076923077 /n
6.147115384615385 /n
6.1923076923076925 /n
6.237500000000001 /n
6.282692307692308 /n
6.327884615384615 /n
6.3730769230769235 /n
6.418269230769231 /n
6.463461538461539 /n
6.508653846153846 /n
6.553846153846154 /n
6.599038461538462 /n
6.644230769230769 /n
6.689423076923077 /n
6.734615384615385 /n
6.779807692307692 /n
6.825 /n
6.870192307692308 /n
6.915384615384616 /n
6.960576923076923 /n
7.005769230769231 /n
7.0509615384615385 /n
7.096153846153847 /n
7.141346153846154 /n
7.186538461538461 /n
7.2317307692307695 /n
7.276923076923077 /n
7.322115384615385 /n
7.367307692307692 /n
7.4125 /n
7.457692307692308 /n
7.502884615384615 /n
7.548076923076923 /n
7.593269230769231 /n
7.638461538461538 /n
7.683653846153846 /n
7.728846153846154 /n
7.774038461538462 /n
7.819230769230769 /n
7.